version: '3.8'
services:
  auth_app:
    container_name: auth_service_app
    build:
      context: ./auth-service
      dockerfile: Dockerfile.local
    restart: always
    ports:
      - 4001:4001
    env_file: ./auth-service/src/configs/.env.development
    environment:
      - DOCKER_ENV=true
  user_app:
    container_name: user_service_app
    build:
      context: ./user-service
      dockerfile: Dockerfile.local
    restart: always
    ports:
      - 4002:4002
    env_file: ./user-service/src/configs/.env.development
    environment:
      - DOCKER_ENV=true
  job_app:
    container_name: job_service_app
    build:
      context: ./job-service
      dockerfile: Dockerfile.local
    restart: always
    ports:
      - 4003:4003
    env_file: ./job-service/src/configs/.env.development
    environment:
      - DOCKER_ENV=true
  
