# Use the correct Node.js 20 Alpine image tag
FROM node:20-alpine3.19

# Set the working directory
WORKDIR /app

# Copy package.json
COPY package.json ./
COPY .npmrc ./

# Install dependencies
RUN npm install && npm install -g nodemon

# Copy other files
COPY tsconfig.json ./
COPY nodemon.json ./
COPY tsoa.json ./

# Copy source code folder
COPY src ./src

# Expose the application's port
EXPOSE 4009

# Command to run the application
CMD ["npm", "run", "dev"]
