import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavigationBar } from "@/components/navigation-bar/navigation-bar";
import Chat from "@/components/chat-home/chat";
import { AuthProvider } from "@/context/auth";
import Notification from "@/components/notification/notification";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cam-formant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Notification />
          <NavigationBar />
          {children}
          <Chat className="fixed bottom-20 right-0 p-4 bg-gradient-to-br from-orange-400 via-pink-300 to-yellow-300 shadow-2xl rounded-full text-white transform transition-transform hover:scale-105" />
        </AuthProvider>
      </body>
    </html>
  );
}
