name: CI/CD Pipeline for Camformant Client

on:
  push:
    branches:
      - main
    paths:
      - "apps/camformant-client/**"
  pull_request:
    branches:
      - main
    paths:
      - "apps/camformant-client/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies for camformant-client
        run: yarn workspace camformant-client install --focus
        working-directory: "./"

      - name: Build the Next.js project
        run: yarn build
        working-directory: "apps/camformant-client"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies for camformant-client
        run: yarn workspace camformant-client install --focus
        working-directory: "./"

      - name: Set Environment Variables
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_AUTH_SERVICE_URL=${{ secrets.NEXT_PUBLIC_AUTH_SERVICE_URL }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_USER_SERVICE_URL=${{ secrets.NEXT_PUBLIC_USER_SERVICE_URL }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_PUSH_NOTIFICATION_SERVICE_URL=${{ secrets.NEXT_PUBLIC_PUSH_NOTIFICATION_SERVICE_URL }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_VAPID_PUBLIC_KEY=${{ secrets.NEXT_PUBLIC_VAPID_PUBLIC_KEY }}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS with SST
        run: npx sst deploy --stage prod
        working-directory: "apps/camformant-client"
