name: CI/CD Pipeline for User Service

on:
  pull_request:
    branches:
      - main
    paths:
      - "apps/backend/user-service/**"
  push:
    branches:
      - main
    paths:
      - "apps/backend/user-service/**"

defaults:
  run:
    working-directory: apps/backend/user-service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use the version of Node.js that your project requires

      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: yarn build

      - name: Run tests
        env:
          MONGODB_URL: ${{ secrets.TEST_MONGODB_URL}}
        run: yarn test

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./apps/backend/user-service/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./apps/backend/user-service/build

      - name: Prepare Deployment Directories
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p /home/ubuntu/apps/user-service/build
            mkdir -p /home/ubuntu/apps/user-service/configs

      - name: Copy files to EC2 using SCP
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -r -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ./apps/backend/user-service/build/* ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/apps/user-service/build/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create .env File
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "${{ secrets.NODE_ENV }}" > /home/ubuntu/apps/user-service/configs/.env.production
            echo "${{ secrets.PORT }}" >> /home/ubuntu/apps/user-service/configs/.env.production
            echo "${{ secrets.MONGODB_URL }}" >> /home/ubuntu/apps/user-service/configs/.env.production

      - name: Install Dependencies and Restart PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/apps/user-service/build
            yarn install --production
            yarn start
